require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5

Rails:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true